version: '3'
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_BASE: "http://localhost:3001/api"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGO_DB_URI: mongodb://mongo:27017
      JWT_SECRET: "test"
      USER_EMAIL: "email@gmail.com"
      USER_PASSWORD: "this-is-my-password"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'